// This file is automatically generated. Do not modify it manually.

export const firebaseConfig = {
  apiKey: "AIzaSyA_I72nJ4F4D33hMXp6v-1234567890",
  authDomain: "dev-s-21951.firebaseapp.com",
  projectId: "dev-s-21951",
  storageBucket: "dev-s-21951.appspot.com",
  messagingSenderId: "931295383461",
  appId: "1:931295383461:web:399c27993a4041b3a505c2",
  measurementId: "G-1B9CJ42F2E",
};
