// This file is automatically generated. Do not modify it manually.

export const firebaseConfig = {
  apiKey: "AIzaSyB-...",
  authDomain: "dev-s-21951.firebaseapp.com",
  projectId: "dev-s-21951",
  storageBucket: "dev-s-21951.appspot.com",
  messagingSenderId: "931295383461",
  appId: "1:931295383461:web:447f22f7457e10eda130e9",
  measurementId: "G-1B9CJ42F2E",
};
